--1) what is the total revenue generated by male vs female customers 
select  gender, sum(purchase_amount) as revenue, count(customer_id)as total_cust
from customer_behavior
group by gender;

-- 2. Subscription Value Analysis — "Is our subscription program actually working?"
SELECT
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(AVG(purchase_amount), 2)     AS avg_purchase_amount_in_USD,
    ROUND(AVG(previous_purchases), 2)  AS avg_previous_purchases,
    ROUND(AVG(review_rating::numeric), 2)       AS avg_review_rating,
    ROUND(SUM(purchase_amount), 2)     AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- 3. Are discounts driving incremental revenue
SELECT
    discount_applied,
    COUNT(*) AS orders,
    ROUND(AVG(purchase_amount), 2)    AS avg_order_value,
    ROUND(AVG(review_rating::numeric), 2)      AS avg_review_rating,
    ROUND(AVG(previous_purchases), 2) AS avg_previous_purchases
FROM customer_behavior
GROUP BY discount_applied;

--4.Deeper cut — discount effectiveness by category
SELECT
    category,
    discount_applied,
    COUNT(*)                       AS orders,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value
FROM customer_behavior
GROUP BY category, discount_applied
ORDER BY category, discount_applied;

--5)do subscribed customers spend more. compare avg spend and total revenue 
--between subscribers and non subscribers 
select subscription_status,avg(purchase_amount)as avg_spend,sum(purchase_amount)
as total_revenue ,count(customer_id) from customer_behavior
group  by subscription_status
order by total_revenue desc;

--6) what are the top 3 most purchased products in each category
with item_count as (
select category,item_purchased,count(item_purchased) as total_orders,
row_number() over (partition by category order by count(item_purchased) desc)
as item_rank from customer_behavior
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3;


